# Generated by Django 4.1.2 on 2022-10-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=254)),
                ('timestamp', models.PositiveIntegerField(null=True)),
                ('payload', models.TextField()),
            ],
        ),
    ]
